version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    image: shinexo1/food_backend/
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - .env

  frontend:
    image: shinexo1/food_frontend/
    env_file:
      - .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: shinexo1/food_gateway/
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    ports:
      - 8000:80

